const ADD_TO_CART = 'ADD_TO_CART';
const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
const DECREASE_AMOUNT = 'DECREASE_AMOUNT';
const CLEAR_CART = 'CLEAR_CART';
const REMOVE_ITEM = 'REMOVE_ITEM';
const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
const UPDATE_TOTAL = 'UPDATE_TOTAL';
export {
  ADD_TO_CART,
  INCREASE_AMOUNT,
  CLEAR_CART,
  REMOVE_ITEM,
  DECREASE_AMOUNT,
  UPDATE_AMOUNT,
  UPDATE_TOTAL,
};
